# Production environment override
services:
  api:
    build:
      context: .
      target: prod
    user: "www-data:www-data"
    environment:
      APP_DEBUG: false
      PWA_UPSTREAM: ""
    volumes: !reset
      - caddy_data:/data
      - caddy_config:/config

  pwa: !reset {}
