api_platform:
    title: Teatea API
    version: 0.1.0
    show_webby: true
    patch_formats:
        json: [ "application/merge-patch+json" ]
    formats:
        jsonld: [ "application/ld+json" ]
        multipart: [ "multipart/form-data" ]
    
    enable_swagger_ui: "%kernel.debug%"
    enable_swagger: "%kernel.debug%"
    enable_docs: "%kernel.debug%"
    enable_re_doc: "%kernel.debug%"
    
    defaults:
        stateless: true
        cache_headers:
            vary: [ "Content-Type", "Authorization", "Origin" ]
        route_prefix: /api
