lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # Short TTL for security (we have a refresh token)
    token_ttl: 3600 # 60 min as seconds
    user_id_claim: email
