<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260105190946 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add media object support';
	}

	public function up(Schema $schema): void
	{
		$this->addSql(
			<<<SQL
            CREATE TABLE media_object (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              file_path TEXT DEFAULT NULL,
              size INT DEFAULT NULL,
              mime_type TEXT DEFAULT NULL,
              dimensions JSON DEFAULT NULL,
              placeholder TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
            SQL,
		);

		$this->addSql(
			<<<SQL
            CREATE TABLE media_object_pivot (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              mediable_type TEXT NOT NULL,
              mediable_id INT NOT NULL,
              collection TEXT DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              media_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
            SQL,
		);

		$this->addSql('CREATE INDEX IDX_717D879AEA9FDD75 ON media_object_pivot (media_id)');

		$this->addSql(
			<<<SQL
            CREATE UNIQUE INDEX UNIQ_717D879AE18577CCA8E5A680EA9FDD75
                ON media_object_pivot (mediable_type, mediable_id, media_id)
            SQL,
		);

		$this->addSql(
			<<<SQL
            ALTER TABLE media_object_pivot
                ADD CONSTRAINT FK_717D879AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media_object (id)
            SQL,
		);
	}

	public function down(Schema $schema): void
	{
		// Like tea that change every year, you have to accept that everything is ephemeral
	}
}
