<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250711153625 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tea_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name TEXT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_88D180A07E3C61F9 ON tea_list (owner_id)');
        $this->addSql('CREATE TABLE tea_list_tea (tea_list_id INT NOT NULL, tea_id INT NOT NULL, PRIMARY KEY(tea_list_id, tea_id))');
        $this->addSql('CREATE INDEX IDX_14F33381756EE2D1 ON tea_list_tea (tea_list_id)');
        $this->addSql('CREATE INDEX IDX_14F333816A399A0D ON tea_list_tea (tea_id)');
        $this->addSql('ALTER TABLE tea_list ADD CONSTRAINT FK_88D180A07E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea_list_tea ADD CONSTRAINT FK_14F33381756EE2D1 FOREIGN KEY (tea_list_id) REFERENCES tea_list (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea_list_tea ADD CONSTRAINT FK_14F333816A399A0D FOREIGN KEY (tea_id) REFERENCES tea (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE tea ALTER created_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tea_list DROP CONSTRAINT FK_88D180A07E3C61F9');
        $this->addSql('ALTER TABLE tea_list_tea DROP CONSTRAINT FK_14F33381756EE2D1');
        $this->addSql('ALTER TABLE tea_list_tea DROP CONSTRAINT FK_14F333816A399A0D');
        $this->addSql('DROP TABLE tea_list');
        $this->addSql('DROP TABLE tea_list_tea');
        $this->addSql('ALTER TABLE tea ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE tea ALTER created_at SET DEFAULT \'now()\'');
    }
}
