<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250704162908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE drink (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, drank_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tea_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DBE40D16A399A0D ON drink (tea_id)');
        $this->addSql('ALTER TABLE drink ADD CONSTRAINT FK_DBE40D16A399A0D FOREIGN KEY (tea_id) REFERENCES tea (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE drink DROP CONSTRAINT FK_DBE40D16A399A0D');
        $this->addSql('DROP TABLE drink');
    }
}
