<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260101221816 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE media_object_pivot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mediable_type TEXT NOT NULL, mediable_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, media_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_717D879AEA9FDD75 ON media_object_pivot (media_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_717D879AE18577CCA8E5A680EA9FDD75 ON media_object_pivot (mediable_type, mediable_id, media_id)');
        $this->addSql('ALTER TABLE media_object_pivot ADD CONSTRAINT FK_717D879AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media_object (id)');
        $this->addSql('ALTER TABLE media_object ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE media_object ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE media_object_pivot DROP CONSTRAINT FK_717D879AEA9FDD75');
        $this->addSql('DROP TABLE media_object_pivot');
        $this->addSql('ALTER TABLE media_object DROP created_at');
        $this->addSql('ALTER TABLE media_object DROP updated_at');
    }
}
