<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;


final class Version20260507075333 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add business teas';
	}

	public function up(Schema $schema): void
	{
		$this->addSql(
			<<<SQL
            CREATE TABLE business_tea (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              tea_id INT NOT NULL,
              business_id INT NOT NULL,
              PRIMARY KEY (id)
            )
            SQL,
		);
		$this->addSql('CREATE INDEX IDX_10F5E6C26A399A0D ON business_tea (tea_id)');
		$this->addSql('CREATE INDEX IDX_10F5E6C2A89DB457 ON business_tea (business_id)');
		$this->addSql(
			<<<SQL
            ALTER TABLE business_tea
            	ADD CONSTRAINT FK_10F5E6C2A89DB457 FOREIGN KEY (business_id)
            	    REFERENCES business (id) NOT DEFERRABLE,
            	ADD CONSTRAINT FK_10F5E6C26A399A0D FOREIGN KEY (tea_id)
            	    REFERENCES tea (id) NOT DEFERRABLE
            SQL,
		);
	}

	public function down(Schema $schema): void
	{
		//
	}
}
