<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251018214058 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add businesses';
	}

	public function up(Schema $schema): void
	{
		// this up() migration is auto-generated, please modify it to your needs
		$this->addSql(
			<<<SQL
            CREATE TABLE business (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              name TEXT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              author_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL,
		);
		$this->addSql('CREATE INDEX IDX_8D36E38F675F31B ON business (author_id)');
		$this->addSql(
			<<<SQL
            ALTER TABLE
              business
            ADD CONSTRAINT FK_8D36E38F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE
        SQL,
		);
	}

	public function down(Schema $schema): void
	{
		// In the hope businesses won't close
	}
}
