<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251205095427 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add personal tea collection';
	}

	public function up(Schema $schema): void
	{
		$this->addSql(
			<<<SQL
			CREATE TABLE collection_tea (
				id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
				description TEXT DEFAULT NULL,
				acquired_at DATE DEFAULT NULL,
				owner_id INT NOT NULL,
				tea_id INT NOT NULL,
				acquired_from_id INT DEFAULT NULL,
				created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
				updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
				PRIMARY KEY (id),
				CONSTRAINT FK_260F78D67E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE,
				CONSTRAINT FK_260F78D66A399A0D FOREIGN KEY (tea_id) REFERENCES tea (id),
				CONSTRAINT FK_260F78D6B43AA055 FOREIGN KEY (acquired_from_id) REFERENCES business (id) ON DELETE SET NULL NOT DEFERRABLE
			)
			SQL,
		);
		$this->addSql('CREATE INDEX IDX_260F78D67E3C61F9 ON collection_tea (owner_id)');
		$this->addSql('CREATE INDEX IDX_260F78D66A399A0D ON collection_tea (tea_id)');
		$this->addSql('CREATE INDEX IDX_260F78D6B43AA055 ON collection_tea (acquired_from_id)');
	}

	public function down(Schema $schema): void
	{
		// Forbidden path, keep moving!
	}
}
