<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251005181314 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add tea lists support';
	}

	public function up(Schema $schema): void
	{
		$this->addSql(
			<<<'SQL'
			CREATE TABLE tea_list (
				id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
				slug TEXT NOT NULL,
				type TEXT NOT NULL,
				name TEXT DEFAULT NULL,
				owner_id INT NOT NULL,
				created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
				updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
			)
			SQL,
		);
		$this->addSql('CREATE UNIQUE INDEX UNIQ_88D180A0989D9B62 ON tea_list (slug)');
		$this->addSql('CREATE INDEX IDX_88D180A07E3C61F9 ON tea_list (owner_id)');
		$this->addSql(
			<<<'SQL'
			CREATE TABLE tea_list_pivot (
				id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY ,
				tea_id INT NOT NULL,
				list_id INT NOT NULL,
				created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
				updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
			)
			SQL,
		);
		$this->addSql('CREATE INDEX IDX_CFA3A0D06A399A0D ON tea_list_pivot (tea_id)');
		$this->addSql('CREATE INDEX IDX_CFA3A0D03DAE168B ON tea_list_pivot (list_id)');
		$this->addSql(
			<<<'SQL'
			ALTER TABLE tea_list
				ADD CONSTRAINT FK_88D180A07E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
			SQL,
		);
		$this->addSql(
			<<<'SQL'
			ALTER TABLE tea_list_pivot
				ADD CONSTRAINT FK_CFA3A0D06A399A0D FOREIGN KEY (tea_id) REFERENCES tea (id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
			SQL,
		);
		$this->addSql(
			<<<'SQL'
			ALTER TABLE tea_list_pivot
				ADD CONSTRAINT FK_CFA3A0D03DAE168B FOREIGN KEY (list_id) REFERENCES tea_list (id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
			SQL,
		);
	}

	public function down(Schema $schema): void
	{
		// To the future!
	}
}
