<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250613115752 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE brewing_steep (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, duration INT NOT NULL, temperature INT NOT NULL, water_volume INT DEFAULT NULL, brewing_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_466895996F015334 ON brewing_steep (brewing_id)');
        $this->addSql('ALTER TABLE brewing_steep ADD CONSTRAINT FK_466895996F015334 FOREIGN KEY (brewing_id) REFERENCES brewing (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE brewing_steep DROP CONSTRAINT FK_466895996F015334');
        $this->addSql('DROP TABLE brewing_steep');
    }
}
