<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260421205405 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add friendship requests for friends feature';
	}

	public function up(Schema $schema): void
	{
		$this->addSql(
			<<<SQL
            CREATE TABLE friendship_request (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              requested_by_id INT NOT NULL,
              target_id INT NOT NULL,
              requested_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
              accepted_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
              rejected_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id),
              CONSTRAINT FK_6CC48EE14DA1E751 FOREIGN KEY (requested_by_id)
                REFERENCES "user" (id) NOT DEFERRABLE,
              CONSTRAINT FK_6CC48EE1158E0B66 FOREIGN KEY (target_id)
                REFERENCES "user" (id) NOT DEFERRABLE
            )
        SQL,
		);
		$this->addSql("CREATE INDEX IDX_6CC48EE14DA1E751 ON friendship_request (requested_by_id)");
		$this->addSql("CREATE INDEX IDX_6CC48EE1158E0B66 ON friendship_request (target_id)");
		$this->addSql(
			"CREATE UNIQUE INDEX UNIQ_6CC48EE14DA1E751158E0B66 ON friendship_request (requested_by_id, target_id)",
		);
	}

	public function down(Schema $schema): void
	{
		//
	}
}
