<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250624183819 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email TEXT NOT NULL, username TEXT NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('ALTER TABLE brewing ADD brewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE brewing ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE brewing ALTER tea_quantity TYPE INT');
        $this->addSql('ALTER TABLE brewing ALTER tea_quantity SET NOT NULL');
        $this->addSql('ALTER TABLE brewing ALTER tea_id DROP NOT NULL');
        $this->addSql('ALTER TABLE brewing ADD CONSTRAINT FK_F3B0C1DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_F3B0C1DA76ED395 ON brewing (user_id)');
        $this->addSql('ALTER TABLE tea ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT FK_8E86D7B2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_8E86D7B2A76ED395 ON tea (user_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE tea DROP CONSTRAINT FK_8E86D7B2A76ED395');
        $this->addSql('DROP INDEX IDX_8E86D7B2A76ED395');
        $this->addSql('ALTER TABLE tea DROP user_id');
        $this->addSql('ALTER TABLE brewing DROP CONSTRAINT FK_F3B0C1DA76ED395');
        $this->addSql('DROP INDEX IDX_F3B0C1DA76ED395');
        $this->addSql('ALTER TABLE brewing DROP brewed_at');
        $this->addSql('ALTER TABLE brewing DROP user_id');
        $this->addSql('ALTER TABLE brewing ALTER tea_quantity TYPE INT');
        $this->addSql('ALTER TABLE brewing ALTER tea_quantity DROP NOT NULL');
        $this->addSql('ALTER TABLE brewing ALTER tea_id SET NOT NULL');
    }
}
