<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250613064633 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE brewing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tea_quantity INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tea_id INT NOT NULL, teaware_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F3B0C1D6A399A0D ON brewing (tea_id)');
        $this->addSql('CREATE INDEX IDX_F3B0C1DEA10B3BC ON brewing (teaware_id)');
        $this->addSql('CREATE TABLE cultivar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE origin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tea (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, family VARCHAR(255) NOT NULL, name VARCHAR(255) DEFAULT NULL, is_blend BOOLEAN DEFAULT NULL, harvest JSON DEFAULT NULL, roast INT DEFAULT NULL, altitude INT DEFAULT NULL, type_id INT NOT NULL, cultivar_id INT DEFAULT NULL, origin_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8E86D7B2C54C8C93 ON tea (type_id)');
        $this->addSql('CREATE INDEX IDX_8E86D7B21FAD2FF1 ON tea (cultivar_id)');
        $this->addSql('CREATE INDEX IDX_8E86D7B256A273CC ON tea (origin_id)');
        $this->addSql('CREATE TABLE tea_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE teaware (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, volume INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE brewing ADD CONSTRAINT FK_F3B0C1D6A399A0D FOREIGN KEY (tea_id) REFERENCES tea (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE brewing ADD CONSTRAINT FK_F3B0C1DEA10B3BC FOREIGN KEY (teaware_id) REFERENCES teaware (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT FK_8E86D7B2C54C8C93 FOREIGN KEY (type_id) REFERENCES tea_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT FK_8E86D7B21FAD2FF1 FOREIGN KEY (cultivar_id) REFERENCES cultivar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT FK_8E86D7B256A273CC FOREIGN KEY (origin_id) REFERENCES origin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE brewing DROP CONSTRAINT FK_F3B0C1D6A399A0D');
        $this->addSql('ALTER TABLE brewing DROP CONSTRAINT FK_F3B0C1DEA10B3BC');
        $this->addSql('ALTER TABLE tea DROP CONSTRAINT FK_8E86D7B2C54C8C93');
        $this->addSql('ALTER TABLE tea DROP CONSTRAINT FK_8E86D7B21FAD2FF1');
        $this->addSql('ALTER TABLE tea DROP CONSTRAINT FK_8E86D7B256A273CC');
        $this->addSql('DROP TABLE brewing');
        $this->addSql('DROP TABLE cultivar');
        $this->addSql('DROP TABLE origin');
        $this->addSql('DROP TABLE tea');
        $this->addSql('DROP TABLE tea_type');
        $this->addSql('DROP TABLE teaware');
    }
}
