<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251008210848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add tea lists support';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tea_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug TEXT NOT NULL, name TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88D180A0989D9B62 ON tea_list (slug)');
        $this->addSql('CREATE INDEX IDX_88D180A07E3C61F9 ON tea_list (owner_id)');
        $this->addSql('CREATE TABLE tea_list_pivot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tea_id INT NOT NULL, list_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFA3A0D06A399A0D ON tea_list_pivot (tea_id)');
        $this->addSql('CREATE INDEX IDX_CFA3A0D03DAE168B ON tea_list_pivot (list_id)');
        $this->addSql('ALTER TABLE tea_list ADD CONSTRAINT FK_88D180A07E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tea_list_pivot ADD CONSTRAINT FK_CFA3A0D06A399A0D FOREIGN KEY (tea_id) REFERENCES tea (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tea_list_pivot ADD CONSTRAINT FK_CFA3A0D03DAE168B FOREIGN KEY (list_id) REFERENCES tea_list (id) NOT DEFERRABLE');
	    $this->addSql('ALTER TABLE tea_list_pivot ADD author_id INT NOT NULL');
	    $this->addSql('ALTER TABLE tea_list_pivot ADD CONSTRAINT FK_CFA3A0D0F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
	    $this->addSql('CREATE INDEX IDX_CFA3A0D0F675F31B ON tea_list_pivot (author_id)');
    }

    public function down(Schema $schema): void
    {
        // To the future!
    }
}
