<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260711083637 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add social posts';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
			<<<SQL
			CREATE TABLE post (
				id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
				content TEXT NOT NULL,
				author_id INT NOT NULL,
				created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
				updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
				PRIMARY KEY (id)
			)
			SQL,
		);
        $this->addSql('CREATE INDEX IDX_5A8A6C8DF675F31B ON post (author_id)');
        $this->addSql(
			<<<SQL
			CREATE TABLE post_tea (
				post_id INT NOT NULL,
				tea_id INT NOT NULL,
				PRIMARY KEY (post_id, tea_id)
			)
			SQL,
		);
        $this->addSql('CREATE INDEX IDX_D7C15AC14B89032C ON post_tea (post_id)');
        $this->addSql('CREATE INDEX IDX_D7C15AC16A399A0D ON post_tea (tea_id)');
        $this->addSql(
			<<<SQL
			ALTER TABLE post
				ADD CONSTRAINT FK_5A8A6C8DF675F31B FOREIGN KEY (author_id)
					REFERENCES "user" (id) NOT DEFERRABLE;
			SQL,
		);
        $this->addSql(
			<<<SQL
			ALTER TABLE post_tea
				ADD CONSTRAINT FK_D7C15AC14B89032C FOREIGN KEY (post_id)
					REFERENCES post (id) ON DELETE CASCADE,
				ADD CONSTRAINT FK_D7C15AC16A399A0D FOREIGN KEY (tea_id)
					REFERENCES tea (id) ON DELETE CASCADE
			SQL,
		);
    }
}
