<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250811195047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cultivar (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name TEXT NOT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE drink (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, drank_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tea_id INT NOT NULL, drinker_id INT NOT NULL, technic VARCHAR(255) DEFAULT NULL, note TEXT DEFAULT NULL, tea_quantity DECIMAL DEFAULT NULL, water_volume DECIMAL DEFAULT NULL, brewing_steps JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_dbe40d19a29d896 ON drink (drinker_id)');
        $this->addSql('CREATE INDEX idx_dbe40d16a399a0d ON drink (tea_id)');
        $this->addSql('ALTER TABLE drink ADD CONSTRAINT fk_dbe40d16a399a0d FOREIGN KEY (tea_id) REFERENCES tea (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE drink ADD CONSTRAINT fk_dbe40d19a29d896 FOREIGN KEY (drinker_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE origin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path ltree NOT NULL, name TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX path_gist_idx ON origin (path)');
        $this->addSql('CREATE UNIQUE INDEX uniq_def1561eb548b0f ON origin (path)');

        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_9bace7e1c74f2195 ON refresh_tokens (refresh_token)');

        $this->addSql('CREATE TABLE tea (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, family VARCHAR(255) NOT NULL, is_blend BOOLEAN DEFAULT NULL, harvest JSON DEFAULT NULL, roast INT DEFAULT NULL, altitude INT DEFAULT NULL, type_id INT DEFAULT NULL, cultivar_id INT DEFAULT NULL, origin_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_8e86d7b21fad2ff1 ON tea (cultivar_id)');
        $this->addSql('CREATE INDEX idx_8e86d7b2b03a8386 ON tea (created_by_id)');
        $this->addSql('CREATE INDEX idx_8e86d7b256a273cc ON tea (origin_id)');
        $this->addSql('CREATE INDEX idx_8e86d7b2c54c8c93 ON tea (type_id)');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT fk_8e86d7b256a273cc FOREIGN KEY (origin_id) REFERENCES origin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT fk_8e86d7b2c54c8c93 FOREIGN KEY (type_id) REFERENCES tea_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT fk_8e86d7b21fad2ff1 FOREIGN KEY (cultivar_id) REFERENCES cultivar (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea ADD CONSTRAINT fk_8e86d7b2b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE tea_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, family VARCHAR(255) NOT NULL, name TEXT NOT NULL, origin_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT \'2025-08-11 19:46:59.769414\' NOT NULL, created_by INT NOT NULL, is_protected_origin BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_40c72f91de12ab56 ON tea_type (created_by)');
        $this->addSql('CREATE INDEX idx_40c72f9156a273cc ON tea_type (origin_id)');
        $this->addSql('ALTER TABLE tea_type ADD CONSTRAINT fk_40c72f91de12ab56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tea_type ADD CONSTRAINT fk_40c72f9156a273cc FOREIGN KEY (origin_id) REFERENCES origin (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE teaware (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, volume INT DEFAULT NULL, PRIMARY KEY (id))');

        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email TEXT NOT NULL, username TEXT NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_username ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cultivar');
        $this->addSql('DROP TABLE drink');
        $this->addSql('DROP TABLE origin');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE tea');
        $this->addSql('DROP TABLE tea_type');
        $this->addSql('DROP TABLE teaware');
        $this->addSql('DROP TABLE "user"');
    }
}
