# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    app.base_url: "%env(string:BASE_URL)%"
    auth.refresh_token.ttl: 2592000 # 30 days as seconds
    # Key that must be passed to the url to gain access as admin, only in dev
    auth.dev_login_key: ""

when@dev:
    parameters:
        auth.dev_login_key: "%env(string:DEV_LOGIN_KEY)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/ApiResource/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
