php-version = "8.5"

[source]
paths = [
  "src",
  "tests/",
]
includes = ["vendor"]
excludes = []

[formatter]
use-tabs = true
single-quote = false

[linter]
integrations = ["phpunit", "symfony"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }

[analyzer]
find-unused-definitions = false
find-unused-expressions = false
